Gis_teach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')), # 7월 22일
    path('articles/', include('articleapp.urls')), # 8월 2일
    path('comments/', include('commentapp.urls')), # 8월 9일
    path('projects/', include('projectapp.urls')), # 8월 12일
    path('subscribes/', include('subscribeapp.urls')), # 8월 19일
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    # 7월 13일
    path('create/', AccountCreateView.as_view(), name='create'), # 2번째 인자는 view 인자를 넣어야함
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # 7월 15일
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # <int:pk> 추가적인 정보 / pk:primary key value

    # 7월 19일
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.

# 6월 28일
#def hello_world(request):
#    return HttpResponse('Hello World')  # 철자 주의할 것 / alt+Enter하면 모듈을 알아서 가져올 수 있음

# 7월 1일
# def hello_world(request): # request : 어디서 요청이 들어왔는지 알 수 있음
#     return render(request, 'base.html')

# 7월 5일
# def hello_world(request):
#     return render(request, 'accountapp/hello_world.html')

# 7월 8일
# def hello_world(request):
#     if request.method == 'POST':
#         return render(request, 'accountapp/hello_world.html',
#                       context={'text':'POST METHOD'})
#     else:
#         return render(request, 'accountapp/hello_world.html',
#                       context={'text':'GET METHOD'})

# 7월 12일
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld


# def hello_world(request):
#     if request.method == 'POST':
#
#         temp = request.POST.get('input_text') # request 안에 POST 내의 값을 가져옴
#
#         new_hello_world = HelloWorld()
#         new_hello_world.text = temp
#         new_hello_world.save() # 데이터 베이스 안에 새로운 행이 만들어짐
#
#         hello_world_list = HelloWorld.objects.all() # 모든 데이터를 가져옴
#
#         # return render(request, 'accountapp/hello_world.html',
#         #               context={'new_hello_world': new_hello_world}) # new_hello_world라는 객체를 넘겨줌
#         return render(request, 'accountapp/hello_world.html',
#                       context={'hello_world_list': hello_world_list})
#     else:
#         hello_world_list = HelloWorld.objects.all()  # 모든 데이터를 가져옴
#         return render(request, 'accountapp/hello_world.html',
#                       context={'hello_world_list':hello_world_list})

from accountapp.models import HelloWorld

# def hello_world(request):
#     if request.user.is_authenticated:
#         if request.method == 'POST':
#             temp = request.POST.get('input_text')  # request 안에 POST 내의 값을 가져옴
#             new_hello_world = HelloWorld()
#             new_hello_world.text = temp
#             new_hello_world.save()  # 데이터 베이스 안에 새로운 행이 만들어짐
#
#             # Get 부분과 중복되는 코드 삭제함
#             # 실행해서 페이지에서 새로고침할 때 중복 코드 입력되는 것을 방지함
#             return HttpResponseRedirect(reverse('accountapp:hello_world'))
#         else:
#             hello_world_list = HelloWorld.objects.all()  # 모든 데이터를 가져옴
#             return render(request, 'accountapp/hello_world.html',
#                           context={'hello_world_list': hello_world_list})
#     else:
#         return HttpResponseRedirect(reverse('accountapp:login'))

# 7월 22일
from articleapp.models import Article


@login_required(login_url=reverse_lazy('accountapp:lonin'))
def hello_world(request):
    if request.method == 'POST':
        temp = request.POST.get('input_text')  # request 안에 POST 내의 값을 가져옴
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()  # 데이터 베이스 안에 새로운 행이 만들어짐

        # Get 부분과 중복되는 코드 삭제함
        # 실행해서 페이지에서 새로고침할 때 중복 코드 입력되는 것을 방지함
        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()  # 모든 데이터를 가져옴
        return render(request, 'accountapp/hello_world.html',
                      context={'hello_world_list': hello_world_list})

# 7월 13일
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User # ctrl + b / 누르면 선언한 곳으로 이동, 파악가능
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world') # 함수형과 클래스형이 부르는 방식이 다름
    template_name = 'accountapp/create.html' #

# 7월 15일
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)

has_ownership = [login_required, account_ownership_required] # 7월 22일

# 7월 19일
@method_decorator(has_ownership, 'get') # 7월 22일
@method_decorator(has_ownership, 'post') # 7월 22일
# @method_decorator(login_required, 'get') # 7월 22일
# @method_decorator(login_required, 'post') # 7월 22일
# @method_decorator(account_ownership_required, 'get') # 7월 22일
# @method_decorator(account_ownership_required, 'post') # 7월 22일
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm # UserCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object})
    # 7월 20일
    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         return super().get(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         return super().post(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_ownership, 'get') # 7월 22일
@method_decorator(has_ownership, 'post') # 7월 22일
# @method_decorator(login_required, 'get') # 7월 22일
# @method_decorator(login_required, 'post') # 7월 22일
# @method_decorator(account_ownership_required, 'get') # 7월 22일
# @method_decorator(account_ownership_required, 'post') # 7월 22일
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

    # 7월 20일
    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         return super().get(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         return super().post(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %} {# 7월 15일 #}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5"> {# m : margin #}
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %} {# 7월 15일 #}
{#                {{ form }}#}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>

    </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit" class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>

    </div>


{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" class='profile_image m-4' alt="profile image">

                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                       class="material-icons round_button">edit</a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
                <h2>
                    <a href="{% url 'profileapp:create' %}">Create Profile</a>
                </h2>
            {% endif %}
        </div>
        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
            class="material-icons round_button mx-1">settings</a>

            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
            class="material-icons round_button mx-1">close</a> {# 마진을 x방향으로 1 #}
        </div>
        {% endif %}
    </div>

    <div>
        {% include  'snippets/list_fragment.html' with article_list=object_list %}
    </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

{#    <style>#}
{#        .testing {#}
{#            background: coral;#}
{#            margin: 1rem;#}
{#            height: 48px; {# 1rem = 18px #}
{#            width: 48px;#}
{#            border-radius: 0.5rem;#}
{#            display: inline-block; {# 7월 8일 추가 #}
{#        }#}
{#    </style>#}

    <div style="margin: 2rem; text-align: center">

        {# 7월 8일 #}
        {# form에서 method로 post를 적어줘야함 #}
{#        <form action="/accounts/hello_world/" method="post">#}
{#            {% csrf_token %} {# POST 방식을 정상적으로 하려면 꼭 적어야함 #}
{#            <input type="submit" class="btn btn-info rounded-pill px-4">#}
{#        </form>#}

        {# GET METHOD #}
{#        <h3>{{ text }}</h3>#}

        {# 7월 12일 #}
        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %} {# POST 방식을 정상적으로 하려면 꼭 적어야함 #}
            <input type="text" name="input_text">
            <input type="submit" class="btn btn-info rounded-pill px-4">
        </form>

        {# GET METHOD #}
{#        <h3>{{ new_hello_world.text }}</h3> {# 객체의 text를 출력 #}

        {% for hello_world in hello_world_list %}
            <h3>{{ hello_world.text }}</h3>
        {% endfor %}


{#    <div class="testing" style="display: block">block</div>#}
{#    <div class="testing" style="display: inline">block</div>#}
{#    <div class="testing" style="display: inline-block">block</div>#}
{#    <div class="testing" style="display: none">block</div>#}
{#    <div class="testing">block</div>#}

    {# 7월 8일 #}
{#    <div class="testing" style="height: 48px; width: 48px">px</div>#}
{#    <div class="testing" style="height: 3rem; width: 3rem">rem</div>#}
{#    <div class="testing" style="height: 3em; width: 3em">em</div>#}
{#    <div class="testing" style="height: 3em; width: 3em">em</div>#}
{#    <div class="testing" style="height: 3em; width: 3em">em</div>#}
{#    <div class="testing" style="height: 3em; width: 3em">em</div>#}
{#    <div class="testing" style="height: 30%; width: 30%">%</div>#}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %} {# 7월 15일 #}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5"> {# m : margin #}
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %} {# 7월 15일 #}
{#                {{ form }}#}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>

    </div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5"> {# m : margin #}
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>

    </div>


{% endblock %}