Gis_teach/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')), # 7월 22일
    path('articles/', include('articleapp.urls')), # 8월 2일
    path('comments/', include('commentapp.urls')), # 8월 9일
    path('projects/', include('projectapp.urls')), # 8월 12일
    path('subscribes/', include('subscribeapp.urls')), # 8월 19일
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    # 7월 13일
    path('create/', AccountCreateView.as_view(), name='create'), # 2번째 인자는 view 인자를 넣어야함
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # 7월 15일
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), # <int:pk> 추가적인 정보 / pk:primary key value

    # 7월 19일
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDetailView.as_view(), name='delete'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subcribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">

{% include 'header.html' %}

{# hr : 줄이 생김 #}
<hr>

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div style="text-align: center">
    <div class="follow_footer_button">
        <span>공지사항</span>
        <span>Intro Service</span>
        <span>제휴문의</span>
    </div>
    <div class="follow_footer_logo">
        {# 'Otomanopee One', sans-serif : 2개 다 Font임 #}
        {# 'Otomanopee One'가 적용 안되면 sans-serif이 적용됨 더 많이 적어줄 수 있음 #}
        <h5>FollowMan</h5>
    </div>
</div>

templates/head.html
{# 내부 파일 가져오기 #}
{% load static %}

{# 외부 라이브러리 가져와 사용할 것이라고 link를 넣어둠 #}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Title</title>

    {# BootStrap Link #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# Google Fonts Link #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">

    {# Static Files Link #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# MATERIAL ICONS Link #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">


    {# 7월 15일 #}
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'), {# 자체 로컬에 해당 파일을 있으면 쓰고 없으면 #}
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype"); {# url에 있는 font를 사용하겠다 #}
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
{# border-radius : 직각의 모서리를 둥글게 만들줌 #}
<div style="text-align: center">
    <div class="follow_header_logo">
        {# margin: 2rem 0; - 2개를 넣으면 2rem은 상하 0은 좌우 #}
        <h1>FollowMan</h1>
    </div>
    <div class="follow_header_button">
        {#span : 좌우로 나열됨#}
        <span>
            <a href="{% url 'articleapp:list' %}">
                Articles
            </a>
        </span>
        <span>
            <a href="{% url 'projectapp:list' %}">
                Projects
            </a>
        </span>
        {% if user.is_authenticated %}
        <span>
            <a href="{% url 'subscribeapp:list' %}">
                Subscription
            </a>
        </span>
        {% endif %}
        {% if not user.is_authenticated %}
        <span>
            <a href="{% url 'accountapp:login' %}">Login</a>
        </span>
        <span>
            <a href="{% url 'accountapp:create' %}">Sign up</a>
        </span>
        {% else %}
        <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">MyPage</a>
        </span>
        <span>
            <a href="{% url 'accountapp:logout' %}">Logout</a>
        </span>
        {% endif %}
    </div>
</div>